### ISSUE TITLE
Cancelable didn't work on Edge

### ISSUE THREAD

**Issue by SemteulGaram** [hmmhmmhm/cancelable-event#2]
Microsoft Edge 44.17763.1.0
Node v11.6.0
cancelable-event 1.0.0
babel-core 7.1.6
babel-preset-env 7.1.6
babel-loader 8.0.4
webpack 4.25.1

My Code:
```
import Cancelable from 'cancelable-event'

class MyProject {
  constructor () {
    ...
    this.dispatcher = new Cancelable({
      async: false,
      trace: true,
      override: true
    })
    ...
  }
}
```

Error:
`Object doesn't support property or method 'getFileName': cancelable.js (13,4)`
![image](https://user-images.githubusercontent.com/6727533/51972163-2b477400-24be-11e9-9fca-4461217d6667.png)

Any help?

**Comment by hmmhmmhm** [comment]
I'll be fix it.
did you tried on chrome?

**Comment by SemteulGaram** [comment]
This module is not a problem ...

https://github.com/felixge/node-stack-trace/issues/19#issue-229293623
"stack-trace" module does not seem to support all browsers except Chrome.

**Comment by hmmhmmhm** [comment]
Exception handling has been applied. Thank you for the report.
